# Generated by Django 4.1 on 2026-02-13 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produk',
            name='harga',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='produk',
            name='id_produk',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
